import type { Metadata } from "next";
import { Inter, Noto_Serif_Display } from "next/font/google";
import "../globals.css";
import RootNavbar from "@/components/root/navbar/RootNavbar";
import RootFooter from "@/components/root/footer/RootFooter";

const notoSerif = Noto_Serif_Display({
  variable: "--font-noto-serif",
  weight: "400",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${notoSerif.variable} antialiased`}>
        <main className="w-full flex flex-col gap-24 justify-center">
          <RootNavbar />
          {children}
          <RootFooter />
        </main>
      </body>
    </html>
  );
}
