import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "../globals.css";

const latoSans = Lato({
  variable: "--font-lato-sans",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${latoSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
